version: "3"
services:
  consul-server:
    image: consul:latest
    ports:
      - "8500"
    environment:
      - CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "ui": true, "dns_config": {"allow_stale": false}}
    commamd: ["agent", "server", "-bind="$(curl -s http://""]
    